import { stops, routePattern, schedule } from './lib/schedule.js';
import { localParts, searchJourneys, journeysForDate, formatTime, formatDate, validDate, rowsForDate, rowMinutes } from './lib/journeys.js';
const main = document.querySelector('#main');
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stop = id => stops.find(s => s.id === id);
const initial = localParts();
let saved = {};
try { saved = JSON.parse(localStorage.getItem('bow-preferences-v2') || '{}') || {}; } catch {}
const state = { origin: stop(saved.origin) ? saved.origin : 'wellesley-campus', destination: stop(saved.destination) ? saved.destination : 'babson-hollister', date: initial.date, time: initial.time, mode: 'leave', preview: false, searched: false, result: null };
if (state.origin === state.destination) state.destination = stops.find(s => s.id !== state.origin).id;
let locationRequest = 0;
function persist() { try { localStorage.setItem('bow-preferences-v2', JSON.stringify({ origin: state.origin, destination: state.destination })); } catch {} }
function header(title, description) { return `<header class="page-heading"><p class="eyebrow">BABSON <span>·</span> OLIN <span>·</span> WELLESLEY</p><h1>${title}</h1><p class="lede">${description}</p></header>`; }
function banner() {
  return state.preview ? `<div class="notice archive"><span class="notice-icon" aria-hidden="true">!</span><div><strong>Archived timetable preview · AY 2025–26</strong><p>Explore the published pattern. Dates do not confirm service or holiday operation.</p></div><button class="text-button" id="exitPreview">Exit preview ↗</button></div>` : `<div class="notice"><span class="notice-icon" aria-hidden="true">!</span><div><strong>Current schedule unconfirmed</strong><p>College timetables disagree. Check the sources before you travel.</p></div><a class="notice-link" href="#service">Service details ↗</a></div>`;
}
function footer() { return `<footer><span>BOWTracker <span class="footer-dot">·</span> Made for the journey between.</span><a href="#service">Scheduled times, not live tracking ↗</a></footer>`; }
function options(selected) { return stops.map(s => `<option value="${s.id}" ${s.id === selected ? 'selected' : ''}>${escape(s.name)}</option>`).join(''); }
function diagram() { return `<aside class="route-panel" aria-label="Shuttle route diagram"><div class="panel-top"><p class="eyebrow">THE BOW LOOP</p><span aria-hidden="true">↗</span></div><h2>Three campuses.<br>A little closer.</h2><p class="route-subtitle">Follow the stops, in order.</p><ol class="route-line">${routePattern.map((id, i) => `<li class="${i > 3 ? 'return-leg' : ''}"><span class="station-dot"></span><span><strong>${escape(stop(id).shortName)}</strong><small>${escape(stop(id).detail)}</small></span>${i === 3 ? '<span class="turn-label">RETURN ↓</span>' : ''}</li>`).join('')}</ol><p class="diagram-note">Route diagram · not a live map</p><a class="underlined" href="#stops">Explore boarding stops <span>↗</span></a></aside>`; }
function tripCard(trip, index) {
  const nextDay = localParts(trip.arrival).date !== localParts(trip.departure).date;
  return `<a class="trip-card ${index === 0 ? 'first' : ''}" href="#journey/${trip.id}" aria-label="View journey leaving ${formatTime(trip.departure)}, destination stop ${formatTime(trip.arrival)}${nextDay ? ' next day' : ''}">${index === 0 ? '<span class="eyebrow">'+(state.mode === 'arrive' ? 'LATEST MATCHING DEPARTURE' : 'FIRST MATCHING DEPARTURE')+'</span>' : ''}<div class="trip-row"><div><h3>${formatTime(trip.departure)} <span class="time-arrow">→</span> ${formatTime(trip.arrival)}${nextDay ? '<small> +1 day</small>' : ''}</h3><p>${trip.duration} min between stops <span>·</span> ${trip.calls.length - 2 ? `${trip.calls.length - 2} intermediate stops` : 'Direct'}</p></div><span class="journey-link">${index === 0 ? 'View journey ' : ''}↗</span></div></a>`;
}
function resultsMarkup() {
  if (!state.searched) return '';
  const r = state.result;
  if (r.status === 'invalid') return `<div class="empty" role="alert"><h2>Check your search</h2><p>${escape(r.message)}</p></div>`;
  if (r.status === 'unconfirmed') return `<div class="empty"><span class="eyebrow">A TIMETABLE YOU CAN TRUST</span><h2>Let's confirm the schedule first.</h2><p>We haven't found a confirmed 2026–27 timetable. Current departures would be a guess, so they're unavailable here.</p><a class="button secondary" href="#service">Compare official sources ↗</a><button class="text-button" data-preview>Explore the archived timetable →</button></div>`;
  if (r.status === 'no-direct-route') return `<div class="empty"><h2>No direct journey in this direction.</h2><p>The published run visits Olin before Babson. A ride through the end of one run into another is not confirmed. Choose a different route or check with the operator.</p><a class="text-button" href="#service">See service details →</a></div>`;
  if (!r.trips.length) return `<div class="empty"><h2>No matching departures.</h2><p>${state.mode === 'arrive' ? 'No journey reaches your stop by this time on the selected date.' : 'No later departure is listed on the selected date.'} Try another time or date. The archived pattern has no Sunday starts and includes driver breaks.</p><button class="text-button" id="earlier">${state.mode === 'arrive' ? 'Show the full day' : 'Search from the start of this day'} →</button></div>`;
  return `<div class="result-heading"><h2>${r.trips.length} scheduled option${r.trips.length === 1 ? '' : 's'}</h2><span>${formatDate(state.date)}</span></div><div class="trip-list">${r.trips.map(tripCard).join('')}</div><p class="fine-print">The PDF lists departure times at every stop. Destination times are scheduled stop calls, not measured arrivals. All times Eastern.</p>`;
}
function findView() {
  main.innerHTML = header('Your campus<br class="desktop-break"> connection.', 'A clearer way to get from here to there.') + banner() + `<div class="planner-grid"><section class="planner-column" aria-label="Journey planner"><form id="planner" class="planner"><div class="section-title"><h2>Where are you headed?</h2><span class="small-tag">${state.preview ? 'TIMETABLE PREVIEW' : 'PLAN A JOURNEY'}</span></div><div class="route-inputs"><label>From<select name="origin">${options(state.origin)}</select></label><button class="swap" id="swap" type="button" aria-label="Swap origin and destination">⇅</button><label>To<select name="destination">${options(state.destination)}</select></label></div><div class="time-inputs"><label>Date<input type="date" name="date" value="${escape(state.date)}" required></label><label><span class="sr-only">Search mode</span><select name="mode" class="mode-select" aria-label="Search mode"><option value="leave" ${state.mode === 'leave' ? 'selected' : ''}>Leave after</option><option value="arrive" ${state.mode === 'arrive' ? 'selected' : ''}>Arrive by</option></select><input type="time" name="time" aria-label="Time in Eastern Time" value="${escape(state.time)}" required></label></div><p class="timezone">◷ All times Eastern · America/New_York</p><button class="button primary full" type="submit">${state.preview ? 'Find scheduled trips' : 'Find a shuttle'} <span>→</span></button></form><section id="results" aria-label="Journey results">${resultsMarkup()}</section>${!state.preview ? `<div class="archive-invite"><div class="archive-symbol" aria-hidden="true">▤</div><div><h2>Get to know the route.</h2><p>Explore the last dated timetable while the current schedule is unconfirmed.</p><button class="text-button" data-preview>Open archived timetable <span>→</span></button></div></div>` : ''}</section>${diagram()}</div>` + footer();
  const form = document.querySelector('#planner');
  form.addEventListener('change', readForm);
  form.addEventListener('submit', e => { e.preventDefault(); readForm(); state.searched = true; state.result = searchJourneys(state); document.querySelector('#results').innerHTML = resultsMarkup(); bindResultActions(); document.querySelector('#results').scrollIntoView({ block: 'nearest', behavior: 'instant' }); });
  document.querySelector('#swap').onclick = () => { readForm(); [state.origin, state.destination] = [state.destination, state.origin]; state.searched = false; persist(); findView(); bindShared(); document.querySelector('#swap').focus(); };
  bindResultActions();
}
function readForm() { const form = document.querySelector('#planner'); if (!form) return; const data = new FormData(form); for (const key of ['origin','destination','date','time','mode']) state[key] = data.get(key); persist(); if (state.searched) { state.searched = false; document.querySelector('#results').innerHTML = '<p class="fine-print">Search updated. Submit the form to refresh results.</p>'; } }
function bindResultActions() { document.querySelectorAll('[data-preview]').forEach(b => b.onclick = enterPreview); const earlier = document.querySelector('#earlier'); if (earlier) earlier.onclick = () => { state.time = state.mode === 'arrive' ? '23:59' : '00:00'; state.result = searchJourneys(state); findView(); bindShared(); }; }
function enterPreview() { state.preview = true; state.date = '2026-04-16'; state.time = '16:00'; state.searched = true; state.result = searchJourneys(state); if (location.hash !== '#find') location.hash = '#find'; else render(); }
function journeyView(id) {
  const pieces = id.split('_');
  const trip = state.preview && validDate(pieces[0]) ? journeysForDate(pieces[0], state.origin, state.destination).find(t => t.id === id) : null;
  if (!trip) { main.innerHTML = header('Start with your route.', 'Choose a journey from the planner to see its stops.') + `<a class="button primary" href="#find">Find a shuttle →</a>` + footer(); return; }
  const origin = stop(trip.origin), destination = stop(trip.destination);
  main.innerHTML = `<a class="back-link" href="#find">← Back to departures</a>` + header(`${escape(origin.shortName)} <span class="heading-arrow">→</span> ${escape(destination.shortName)}`, formatDate(trip.serviceDate)) + banner() + `<div class="detail-grid"><section class="journey-panel"><p class="eyebrow">YOUR SCHEDULED JOURNEY</p><h2 class="journey-time">${formatTime(trip.departure)} <span>→</span> ${formatTime(trip.arrival)}</h2><p class="journey-duration">${trip.duration} min between stops${localParts(trip.arrival).date !== trip.serviceDate ? ' · destination stop on '+formatDate(localParts(trip.arrival).date) : ''}</p><ol class="journey-timeline">${trip.calls.map((c,i) => `<li><time>${formatTime(c.at)}</time><span class="timeline-dot"></span><div><strong>${escape(stop(c.stopId).name)}</strong><small>${i === 0 ? 'Board here' : i === trip.calls.length - 1 ? 'Your destination · scheduled stop time' : 'Intermediate stop'}</small></div></li>`).join('')}</ol><a class="button primary full" href="#stops/${trip.origin}">Find boarding stop <span>↗</span></a><p class="fine-print">The operator asks riders to be at the stop at least five minutes before departure. These archived times do not confirm current service.</p></section><aside class="detail-aside"><div class="note-card"><span class="eyebrow">A LITTLE CLARITY</span><h2>A schedule,<br>not a moving bus.</h2><p>Every time here comes from the published timetable. We don't have a verified vehicle feed, so traffic delays and bus location aren't shown.</p><a class="underlined" href="#service">Where the times come from ↗</a></div><div class="small-note"><h3>Returning later?</h3><p>Plan your return separately: the loop's return leg does not stop at Olin.</p><button class="text-button" id="returnRoute">Plan the reverse route →</button></div></aside></div>` + footer();
  document.querySelector('#returnRoute').onclick = () => { [state.origin,state.destination] = [state.destination,state.origin]; state.searched = false; persist(); location.hash = '#find'; };
}
function mapUrl(s) { return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name+', Massachusetts')}`; }
function stopsView(selected) {
  main.innerHTML = header('Find your stop.', 'Four boarding locations. One shared campus loop.') + (state.preview ? banner() : '') + `<div class="stops-intro"><p>Use the official stop name to find your way. Map links open a place search; confirm the signed boarding point when you arrive.</p><button class="button secondary" id="locate">⌖ Suggest a nearby stop</button></div><div id="locationStatus" role="status"></div><div class="stop-grid">${stops.map((s,i) => `<article class="stop-card ${selected === s.id ? 'selected-stop' : ''}" id="${s.id}"><div class="stop-top"><span class="stop-number">0${i+1}</span><span class="small-tag">${i < 2 ? 'WELLESLEY' : s.shortName.toUpperCase()}</span></div><h2>${escape(s.shortName)}</h2><p class="stop-detail">${escape(s.detail)}</p><p class="stop-direction">${s.id === 'wellesley-founders' ? 'Served on both legs. Check your journey direction.' : s.id === 'olin-east' ? 'Served before Babson on the outbound leg.' : s.id === 'babson-hollister' ? 'Return leg continues to Founders and Wellesley.' : 'Start and end of the published loop.'}</p><div class="stop-actions"><a class="underlined" href="${mapUrl(s)}" target="_blank" rel="noreferrer">Open map search ↗</a><button class="text-button" data-origin="${s.id}">Leave from here →</button></div></article>`).join('')}</div><p class="fine-print">Location is optional, requested only when you choose it, and never stored. Suggestions use approximate stop coordinates; they are not walking directions.</p>` + footer();
  document.querySelectorAll('[data-origin]').forEach(b => b.onclick = () => { state.origin = b.dataset.origin; if(state.destination === state.origin) state.destination = stops.find(s => s.id !== state.origin).id; state.searched=false; persist(); location.hash='#find'; });
  document.querySelector('#locate').onclick = locate;
  if (selected && stop(selected)) document.getElementById(selected).scrollIntoView({block:'nearest'});
}
function distance(a,b) { const rad=x=>x*Math.PI/180; const dlat=rad(b.lat-a.lat), dlon=rad(b.lon-a.lon); const h=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2; return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)); }
function locate() {
  const el = document.querySelector('#locationStatus'); const request = ++locationRequest;
  const show = html => { if (request === locationRequest && el.isConnected) el.innerHTML = html; };
  if (!navigator.geolocation) { show('<p class="location-message">Location is unavailable in this browser. Choose a stop below.</p>'); return; }
  show('<p class="location-message">Finding a nearby stop… Your browser will ask for permission.</p>');
  navigator.geolocation.getCurrentPosition(position => {
    const {latitude:lat,longitude:lon,accuracy} = position.coords;
    if (![lat,lon,accuracy].every(Number.isFinite) || accuracy > 500 || accuracy < 0 || Math.abs(lat) > 90 || Math.abs(lon) > 180) { show('<p class="location-message">This location is too imprecise to suggest a stop. Choose one below.</p>'); return; }
    const nearby = stops.map(s=>({s,metres:distance({lat,lon},s)})).sort((a,b)=>a.metres-b.metres)[0];
    if(nearby.metres > 3000) { show('<p class="location-message">You seem to be away from the campuses. Choose your boarding stop below.</p>'); return; }
    show(`<div class="location-message"><strong>${escape(nearby.s.name)} may be nearby.</strong><p>About ${Math.round(nearby.metres/100)*100} m in a straight line · device accuracy ±${Math.round(accuracy)} m. Stop coordinates are approximate.</p><button class="button secondary" id="confirmStop">Use this as my origin</button></div>`);
    const button = el.querySelector('#confirmStop'); if(button) button.onclick = () => {state.origin=nearby.s.id;if(state.destination===state.origin)state.destination=stops.find(s=>s.id!==state.origin).id;state.searched=false;persist();location.hash='#find';};
  }, error => show(`<p class="location-message">${error.code === 1 ? 'Location permission was declined.' : 'Your location could not be determined.'} You can still choose any stop below.</p>`), {enableHighAccuracy:true,timeout:10000,maximumAge:60000});
}
function serviceView() {
  main.innerHTML = header('Know before you go.', 'The sources, the schedule, and what still needs confirming.') + `<div class="notice"><span class="notice-icon" aria-hidden="true">!</span><div><strong>2026–27 service is not confirmed here</strong><p>Sources checked September 22, 2026. This app is independent of the colleges and operator.</p></div></div><div class="service-grid"><section class="source-card"><span class="eyebrow">THE LAST DATED SOURCE</span><h2>Babson · AY 2025–26</h2><p>Babson's transportation page still links this PDF. It provides a full timetable, but does not establish current-year service.</p><a class="underlined" href="${schedule.sourceUrl}" target="_blank" rel="noreferrer">Open official PDF ↗</a></section><section class="source-card"><span class="eyebrow">AN UNDATED SOURCE</span><h2>Wellesley · shuttle page</h2><p>The online table differs on late-service days and a midday trip. An undated page is not enough to settle the discrepancy.</p><a class="underlined" href="${schedule.wellesleyUrl}" target="_blank" rel="noreferrer">Open Wellesley's schedule ↗</a></section></div><section class="conflicts"><h2>Two differences that matter.</h2><div class="table-scroll" tabindex="0" role="region" aria-label="Schedule comparison"><table><caption class="sr-only">Conflicting official shuttle schedule details</caption><thead><tr><th>Service detail</th><th>Babson PDF · 2025–26</th><th>Wellesley · undated</th></tr></thead><tbody><tr><th>Extended evenings</th><td>Thursday & Friday</td><td>Tuesday & Thursday</td></tr><tr><th>Midday from Wellesley</th><td>12:40 pm</td><td>12:10 pm</td></tr></tbody></table></div></section><div class="service-grid"><section class="note-card"><span class="eyebrow">CHECK BEFORE TRAVEL</span><h2>Ask the operator.</h2><p>Wellesley lists JFK Transportation as the BOW shuttle operator. Confirm the current timetable, holiday service, and your boarding point.</p><a class="button primary" href="tel:+15086534500">Call 508-653-4500 ↗</a></section><section class="source-card"><span class="eyebrow">EXPLORE THE PATTERN</span><h2>The archived timetable.</h2><p>Browse the complete published rows, including breaks and Saturday's midnight finish. Preview dates are illustrative; the service calendar is unverified.</p><button class="button secondary" data-preview>Try a sample journey →</button></section></div><section class="timetable-section"><div class="section-title"><h2>AY 2025–26 timetable</h2><label class="table-selector">Service pattern<select id="tableDay"><option value="2026-04-13">Mon–Wed</option><option value="2026-04-16">Thu–Fri</option><option value="2026-04-18">Saturday</option></select></label></div><p class="fine-print">Archived · all times Eastern · every cell is a scheduled departure at that stop. No Sunday starts are listed. Breaks are gaps between rows.</p><div class="table-scroll" id="timetable" tabindex="0" role="region" aria-label="Scrollable archived timetable"></div></section>` + footer();
  const table = () => { const rows = rowsForDate(document.querySelector('#tableDay').value); document.querySelector('#timetable').innerHTML = `<table><caption class="sr-only">Archived full shuttle timetable</caption><thead><tr>${['Wellesley','Founders →','Olin','Babson','Founders ←','Wellesley'].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((t,i)=>`<td>${t}${rowMinutes(row)[i]>=1440?' +1 day':''}</td>`).join('')}</tr>`).join('')}</tbody></table>`; };
  document.querySelector('#tableDay').onchange = table; table();
}
function bindShared() {
  renderConnectionState();
  document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=enterPreview);
  const exit = document.querySelector('#exitPreview'); if(exit)exit.onclick=()=>{state.preview=false;state.searched=false;Object.assign(state,{date:localParts().date,time:localParts().time});if(location.hash!=='#find')location.hash='#find';else render();};
}
function render() {
  locationRequest++;
  const [view, id] = location.hash.slice(1).split('/');
  document.querySelectorAll('[data-nav]').forEach(a=>{ const active=a.dataset.nav===(view==='journey'?'find':view||'find'); a.toggleAttribute('aria-current',active); if(active)a.setAttribute('aria-current','page'); });
  if(view==='journey') journeyView(id || ''); else if(view==='stops') stopsView(id); else if(view==='service') serviceView(); else findView();
  bindShared();
  document.title = `BOWTracker · ${view==='stops'?'Stops':view==='service'?'Schedule & service':view==='journey'?'Your journey':'Your campus connection'}`;
}
window.addEventListener('hashchange',()=>{render();main.focus();window.scrollTo(0,0);});
function renderConnectionState() {
  document.querySelector('#offlineNotice')?.remove();
  if (navigator.onLine !== false) return;
  const notice = document.createElement('p');
  notice.id = 'offlineNotice';
  notice.className = 'offline';
  notice.setAttribute('role', 'status');
  notice.textContent = 'You’re offline. The loaded archive still works; official sources and map links need a connection.';
  main.prepend(notice);
}
window.addEventListener('online', renderConnectionState);
window.addEventListener('offline', renderConnectionState);
render();
